/** Represents a file and its metadata within the project. */
export interface DependencyNode {
  id: string;
  relativePath: string;
  isEntryPoint: boolean;
  language: "typescript" | "javascript";
}

/** Represents a connection (import/export) between two files. */
export interface DependencyEdge {
  from: string;
  to: string;
  kind: "static" | "dynamic" | "re-export";
}

/** Represents the complete graph structure of project dependencies. */
export interface Graph {
  nodes: Map<string, DependencyNode>;
  edges: DependencyEdge[];
  neighborsOf(id: string): string[];
  incomingTo(id: string): string[];
}

/** Represents a warning or issue found during analysis. */
export interface Warning {
  file: string;
  message: string;
}

/** Represents the predicted impact of modifying a specific file. */
export interface ImpactReport {
  target: string;
  directlyAffected: string[];
  allAffected: string[];
  isSafeToDelete: boolean;
}

/** Represents the resolved configuration settings for the tool. */
export interface ResolvedConfig {
  entryPoints: string[];
  ignore: string[];
  extensions: string[];
}

/** The final output object generated by the analysis engine. */
export interface AnalysisResult {
  version: string;
  generatedAt: string;
  projectRoot: string;
  nodes: DependencyNode[];
  edges: DependencyEdge[];
  cycles: string[][];
  deadFiles: string[];
  entryPoints: string[];
  impact: Record<string, ImpactReport>;
  warnings: Warning[];
}

/** Custom error class for handling domain-specific errors in Cascade. */
export class CascadeError extends Error {
  constructor(
    public code: "PARSE_ERROR" | "CONFIG_ERROR" | "FILE_NOT_FOUND",
    message: string,
    public filePath?: string
  ) {
    super(message);
    this.name = "CascadeError";
  }
}
