import path from "node:path";
import { describe, expect, it } from "vitest";
import { createGoPlugin, extractGoDependencies } from "@cascade-code/language-go";

describe("Go language plugin", () => {
  it("extracts grouped, aliased, blank, and cgo imports from the syntax tree", () => {
    const result = extractGoDependencies(
      "cmd/service/main.go",
      `//go:build linux
package main
/*
#include <stdlib.h>
*/
import "C"
import (
  j "encoding/json"
  _ "example.com/driver"
  "example.com/service/internal/log"
)
`
    );
    expect(result.dependencies.map((dependency) => dependency.specifier)).toEqual([
      "C",
      "encoding/json",
      "example.com/driver",
      "example.com/service/internal/log",
    ]);
    expect(
      result.dependencies.find((dependency) => dependency.specifier === "example.com/driver")
    ).toMatchObject({ importKind: "side-effect", importedNames: ["_"] });
    expect(result.dependencies.find((dependency) => dependency.specifier === "C")).toMatchObject({
      importKind: "reference",
    });
    expect(result.diagnostics[0]?.code).toBe("GO_BUILD_CONSTRAINT");
  });

  it("preserves parser diagnostics and detects tests and generated sources", () => {
    const plugin = createGoPlugin();
    expect(
      plugin.parser.parse({
        filePath: "broken.go",
        relativePath: "broken.go",
        content: "package broken\nfunc x( {",
      })
    ).toMatchObject({ status: "partial" });
    expect(plugin.testFileDetector?.isTestFile("thing_test.go", "thing_test.go")).toBe(true);
    expect(
      plugin.generatedFileDetector?.isGeneratedFile(
        "client.go",
        "api/client.go",
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api"
      )
    ).toBe(true);
  });

  it("resolves module packages, local replacements, standard library, external, and missing imports", () => {
    const root = path.resolve("tests/fixtures/go/workspace");
    const plugin = createGoPlugin();
    const base = {
      importerFilePath: path.join(root, "service/cmd/server/main.go"),
      importerRelativePath: "service/cmd/server/main.go",
      projectRoot: root,
      allKnownFiles: [
        "service/cmd/server/main.go",
        "service/internal/log/log.go",
        "shared/client/client.go",
      ],
    };
    const resolve = (specifier: string) =>
      plugin.moduleResolver.resolveModule({
        ...base,
        specifier,
        extractedDependency: {
          specifier,
          importKind: "static",
          isStatic: true,
          isDynamic: false,
          isTypeOnly: false,
          isReExport: false,
          isConditional: false,
        },
      });
    expect(resolve("example.com/service/internal/log")).toMatchObject({
      resolutionStatus: "resolved",
      dependencyCategory: "internal",
    });
    expect(resolve("example.com/shared/client")).toMatchObject({
      resolutionStatus: "resolved",
      dependencyCategory: "internal",
    });
    expect(resolve("net/http")).toMatchObject({
      resolutionStatus: "external",
      dependencyCategory: "standard-library",
    });
    expect(resolve("github.com/google/uuid")).toMatchObject({
      resolutionStatus: "external",
      dependencyCategory: "external",
    });
    expect(resolve("missing")).toMatchObject({
      resolutionStatus: "unresolved",
      dependencyCategory: "unresolved",
    });
  });

  it("detects only package-main files containing func main as entry points", () => {
    const root = path.resolve("tests/fixtures/go/module");
    const plugin = createGoPlugin();
    const hints = plugin.entryPointHints?.detectEntryPoints(root, [
      "cmd/tool/main.go",
      "pkg/greet/greet.go",
      "pkg/greet/greet_test.go",
    ]);
    expect(hints).toEqual([
      expect.objectContaining({ relativePath: "cmd/tool/main.go", confidence: 1 }),
    ]);
  });

  it("reports go.work use directories as structured workspace metadata", () => {
    const root = path.resolve("tests/fixtures/go/workspace");
    const plugin = createGoPlugin();
    expect(
      plugin.frameworkMetadata?.detectMetadata(root, [
        "service/cmd/server/main.go",
        "shared/client/client.go",
      ])
    ).toContainEqual({
      frameworkName: "Go workspace",
      metadata: expect.objectContaining({ useDirectories: ["./service", "./shared"] }),
    });
  });
});
